name: Build and deploy container app to Azure Web App - webchatapp

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image locally
        run: |
          docker build -t webchatapp-image:${{ github.sha }} \
          --build-arg VITE_SOCKET_URL="https://webchatapp.azurewebsites.net" \
          --build-arg VITE_API_URL="https://webchatapp.azurewebsites.net" \
          --build-arg VITE_GOOGLE_CLIENT_ID="499832833774-cnt8rhtb7m0skk7h1eueqlq7juvm9g.apps.googleusercontent.com" .
          docker save webchatapp-image:${{ github.sha }} > webchatapp.tar

      - name: Upload image as artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: webchatapp.tar
          retention-days: 1

  deploy:
    runs-on: ubuntu-latest
    needs: build
    # OIDC Token generation ke liye permissions
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download image from build job
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_A921255B2331476BA94BE6736C887D91 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_3DAD0F90A8D5419EBD533070320AD85E }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_2FB0AA5F31EC4429B5F62C03C409FDAD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webchatapp'
          images: 'webchatapp-image:${{ github.sha }}'